language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem i activesupport
- gem install cocoapods
- gem i slather --no-rdoc
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
script:
- set -o pipefail && xcodebuild test -workspace Example/FormTableView.xcworkspace -scheme FormTableView-Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
after_success: slather
